In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print ("Retail Sales Analysis")

Retail Sales Analysis

In [2]:
import sys
print(sys.executable)

/usr/local/bin/python3

# Project 1: Retail Store Sales & Customer Analysis

What is the business problem?

## Business Problem

A retail store wants to better understand its sales performance and customer purchasing behaviour. The objective is to analyse transaction data to identify sales trends, customer demographics, and product category performance that can support business decisions.

## 1. Import Libraries

The analysis will use Python libraries for data manipulation and visualization.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Make plots appear in the notebook
%matplotlib inline

# Optional: slightly larger default figure size
plt.rcParams["figure.figsize"] = (10, 6)

## 2. Load Dataset

### Business Question

What information is available in the retail transaction dataset?

In [4]:
# Load the dataset
df = pd.read_csv("../data/retail_sales_dataset.csv")

# Display the first 5 rows
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

### Initial Observation

The dataset contains transaction-level retail information including customer demographics, product categories, quantity purchased, price per unit, and total transaction amount.

## 3. Data Overview

### Business Question

How large is the dataset and how many variables are available for analysis?

In [ ]:
# Number of rows and columns
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

### Interpretation

The dataset contains 1,000 transactions and 9 variables.

Each row represents one customer transaction, while each column provides information about customer characteristics, purchased products, and sales details.

### Business Insight

The dataset provides enough transaction records to explore customer behaviour, product category performance, and sales trends.

## 4. Data Understanding

### Business Question

What is the structure and quality of the retail dataset?

We will inspect:
- Column names
- Data types
- Missing values
- Number of non-null records

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

### Interpretation

The dataset contains 1,000 transactions and 9 columns.

The dataset includes:
- Numerical variables such as age, quantity, price per unit, and total amount.
- Categorical variables such as gender and product category.
- Date information stored as text, which will need to be converted into a date format for time-based analysis.

No missing values were identified, so the dataset does not require missing value treatment.